export { supabase, supabaseAdmin, getServerClient } from './client';
export type {
  Database,
  Json,
  Client,
  ClientInsert,
  ClientUpdate,
  Location,
  LocationInsert,
  LocationUpdate,
  ResearchResults,
  ResearchResultsInsert,
  ResearchResultsUpdate,
  Analysis,
  AnalysisInsert,
  AnalysisUpdate,
  ResearchSession,
  ResearchSessionInsert,
  ResearchSessionUpdate,
  ResearchStatus,
  ClientWithResearch,
  ClientWithLocations,
} from './types';
